<?php

/**
 * Static snapshot of the ext-glfw 0.5.0 method lists.
 * Generated from .zep sources; lets the coverage drift test run
 * without the extension loaded. Regenerate when the extension updates.
 */

return array (
  'Glfw\\GLFW\\GLFW' => 
  array (
    0 => 'glfwGetPlatform',
    1 => 'glfwGetVersion',
    2 => 'glfwGetVersionString',
    3 => 'glfwInit',
    4 => 'glfwInitAllocator',
    5 => 'glfwInitHint',
    6 => 'glfwInitVulkanLoader',
    7 => 'glfwPlatformSupported',
    8 => 'glfwSetErrorCallback',
    9 => 'glfwTerminate',
  ),
  'Glfw\\GLFW\\GLFWError' => 
  array (
    0 => 'glfwGetError',
  ),
  'Glfw\\GLFW\\Window\\GLFWWindow' => 
  array (
    0 => 'glfwCreateWindow',
    1 => 'glfwDefaultWindowHints',
    2 => 'glfwDestroyWindow',
    3 => 'glfwFocusWindow',
    4 => 'glfwGetFramebufferSize',
    5 => 'glfwGetWindowAttrib',
    6 => 'glfwGetWindowContentScale',
    7 => 'glfwGetWindowFrameSize',
    8 => 'glfwGetWindowMonitor',
    9 => 'glfwGetWindowOpacity',
    10 => 'glfwGetWindowPos',
    11 => 'glfwGetWindowSize',
    12 => 'glfwGetWindowTitle',
    13 => 'glfwGetWindowUserPointer',
    14 => 'glfwHideWindow',
    15 => 'glfwIconifyWindow',
    16 => 'glfwMaximizeWindow',
    17 => 'glfwPollEvents',
    18 => 'glfwPostEmptyEvent',
    19 => 'glfwRequestWindowAttention',
    20 => 'glfwRestoreWindow',
    21 => 'glfwSetFramebufferSizeCallback',
    22 => 'glfwSetWindowAspectRatio',
    23 => 'glfwSetWindowAttrib',
    24 => 'glfwSetWindowCloseCallback',
    25 => 'glfwSetWindowContentScaleCallback',
    26 => 'glfwSetWindowFocusCallback',
    27 => 'glfwSetWindowIcon',
    28 => 'glfwSetWindowIconifyCallback',
    29 => 'glfwSetWindowMaximizeCallback',
    30 => 'glfwSetWindowMonitor',
    31 => 'glfwSetWindowOpacity',
    32 => 'glfwSetWindowPos',
    33 => 'glfwSetWindowPosCallback',
    34 => 'glfwSetWindowRefreshCallback',
    35 => 'glfwSetWindowShouldClose',
    36 => 'glfwSetWindowSize',
    37 => 'glfwSetWindowSizeCallback',
    38 => 'glfwSetWindowSizeLimits',
    39 => 'glfwSetWindowTitle',
    40 => 'glfwSetWindowUserPointer',
    41 => 'glfwShowWindow',
    42 => 'glfwWaitEvents',
    43 => 'glfwWaitEventsTimeout',
    44 => 'glfwWindowHint',
    45 => 'glfwWindowHintString',
    46 => 'glfwWindowShouldClose',
  ),
  'Glfw\\GLFW\\Monitor\\GLFWMonitor' => 
  array (
    0 => 'glfwGetGammaRamp',
    1 => 'glfwGetMonitorContentScale',
    2 => 'glfwGetMonitorName',
    3 => 'glfwGetMonitorPhysicalSize',
    4 => 'glfwGetMonitorPos',
    5 => 'glfwGetMonitorUserPointer',
    6 => 'glfwGetMonitorWorkarea',
    7 => 'glfwGetMonitors',
    8 => 'glfwGetPrimaryMonitor',
    9 => 'glfwGetVideoMode',
    10 => 'glfwGetVideoModes',
    11 => 'glfwSetGamma',
    12 => 'glfwSetGammaRamp',
    13 => 'glfwSetMonitorCallback',
    14 => 'glfwSetMonitorUserPointer',
  ),
  'Glfw\\GLFW\\Input\\GLFWInput' => 
  array (
    0 => 'glfwCreateCursor',
    1 => 'glfwCreateStandardCursor',
    2 => 'glfwDestroyCursor',
    3 => 'glfwGetClipboardString',
    4 => 'glfwGetCursorPos',
    5 => 'glfwGetGamepadName',
    6 => 'glfwGetGamepadState',
    7 => 'glfwGetInputMode',
    8 => 'glfwGetJoystickAxes',
    9 => 'glfwGetJoystickButtons',
    10 => 'glfwGetJoystickGUID',
    11 => 'glfwGetJoystickHats',
    12 => 'glfwGetJoystickName',
    13 => 'glfwGetJoystickUserPointer',
    14 => 'glfwGetKey',
    15 => 'glfwGetKeyName',
    16 => 'glfwGetKeyScancode',
    17 => 'glfwGetMouseButton',
    18 => 'glfwGetTime',
    19 => 'glfwGetTimerFrequency',
    20 => 'glfwGetTimerValue',
    21 => 'glfwJoystickIsGamepad',
    22 => 'glfwJoystickPresent',
    23 => 'glfwRawMouseMotionSupported',
    24 => 'glfwSetCharCallback',
    25 => 'glfwSetCharModsCallback',
    26 => 'glfwSetClipboardString',
    27 => 'glfwSetCursor',
    28 => 'glfwSetCursorEnterCallback',
    29 => 'glfwSetCursorPos',
    30 => 'glfwSetCursorPosCallback',
    31 => 'glfwSetDropCallback',
    32 => 'glfwSetInputMode',
    33 => 'glfwSetJoystickCallback',
    34 => 'glfwSetJoystickUserPointer',
    35 => 'glfwSetKeyCallback',
    36 => 'glfwSetMouseButtonCallback',
    37 => 'glfwSetScrollCallback',
    38 => 'glfwSetTime',
    39 => 'glfwUpdateGamepadMappings',
  ),
  'Glfw\\GLFW\\Context\\GLFWContext' => 
  array (
    0 => 'glfwExtensionSupported',
    1 => 'glfwGetCurrentContext',
    2 => 'glfwGetProcAddress',
    3 => 'glfwMakeContextCurrent',
    4 => 'glfwSwapBuffers',
    5 => 'glfwSwapInterval',
  ),
  'Glfw\\GLFW\\Vulkan\\GLFWVulkan' => 
  array (
    0 => 'glfwCreateWindowSurface',
    1 => 'glfwGetInstanceProcAddress',
    2 => 'glfwGetPhysicalDevicePresentationSupport',
    3 => 'glfwGetRequiredInstanceExtensions',
    4 => 'glfwVulkanSupported',
  ),
  'Glfw\\GLFW\\GL\\GLFWGL' => 
  array (
    0 => 'glClear',
    1 => 'glClearColor',
    2 => 'glDisable',
    3 => 'glEnable',
    4 => 'glGetError',
    5 => 'glGetString',
    6 => 'glScissor',
    7 => 'glViewport',
  ),
);
